import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-server';

// =============================================
// Request Body Shape
// =============================================
interface CheckoutItem {
  productId: string;
  variantId: string;
  quantity: number;
  podCustomizations: Record<string, string> | null;
}

interface CheckoutRequest {
  items: CheckoutItem[];
  shipping: {
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    addressLine1: string;
    city: string;
    province: string;
  };
  gateway: 'jazzCash' | 'easyPaisa' | 'xpay';
}

// =============================================
// Shipping cost (flat-rate MVP)
// =============================================
const SHIPPING_PKR = 250;

export async function POST(req: NextRequest) {
  try {
    const body: CheckoutRequest = await req.json();
    const { items, shipping, gateway } = body;

    // — Validation —
    if (!items?.length) {
      return NextResponse.json({ error: 'Cart is empty.' }, { status: 400 });
    }
    if (!shipping?.customerEmail || !shipping?.customerName) {
      return NextResponse.json({ error: 'Missing shipping details.' }, { status: 400 });
    }
    if (!['jazzCash', 'easyPaisa', 'xpay'].includes(gateway)) {
      return NextResponse.json({ error: 'Invalid payment gateway.' }, { status: 400 });
    }

    // =============================================
    // SECURITY: Re-fetch product prices server-side.
    // We NEVER trust the price sent from the client.
    //
    // Exception: Custom POD items (productId starts with "custom-")
    // are generated by the Design Studio and have no DB row.
    // Their price is fixed server-side at POD_PRICE_PKR.
    // =============================================
    const POD_PRICE_PKR = 5500;

    const regularItems  = items.filter((i) => !i.productId.startsWith('custom-'));
    const customPodItems = items.filter((i) =>  i.productId.startsWith('custom-'));

    // Fetch only real products from the DB
    let productMap = new Map<string, { title: string; base_price: number; image_url: string | null; is_pod: boolean; is_active: boolean }>();

    if (regularItems.length > 0) {
      const productIds = [...new Set(regularItems.map((i) => i.productId))];

      const { data: products, error: productError } = await supabaseAdmin
        .from('products')
        .select('id, base_price, title, image_url, is_pod, is_active')
        .in('id', productIds);

      if (productError || !products) {
        console.error('[checkout] Product fetch error:', productError);
        return NextResponse.json({ error: 'Could not verify products.' }, { status: 500 });
      }

      // Reject if any regular product is inactive / not found
      productMap = new Map(products.map((p) => [p.id, p]));
      for (const item of regularItems) {
        const product = productMap.get(item.productId);
        if (!product || !product.is_active) {
          return NextResponse.json(
            { error: `Product "${item.productId}" is unavailable.` },
            { status: 400 }
          );
        }
      }
    }

    // =============================================
    // Calculate server-verified total
    // =============================================
    let subtotal = 0;

    const verifiedRegular = regularItems.map((item) => {
      const product = productMap.get(item.productId)!;
      const unitPrice = Number(product.base_price);
      subtotal += unitPrice * item.quantity;
      return {
        product_id:        item.productId,
        variant_id:        item.variantId,
        product_title:     product.title,
        product_image_url: product.image_url,
        quantity:          item.quantity,
        unit_price_pkr:    unitPrice,
        pod_customization: item.podCustomizations ?? null,
        is_pod:            product.is_pod,
      };
    });

    // Custom POD items — price is hardcoded server-side, never from client.
    // The order_items.product_id column is NOT NULL + FK to products,
    // so we can't insert NULL. Instead, we upsert a single sentinel
    // "Custom POD Template" row in the products table and use its real UUID.
    let podProductId: string | null = null;

    if (customPodItems.length > 0) {
      // Try to find the existing sentinel row
      const { data: existing } = await supabaseAdmin
        .from('products')
        .select('id')
        .eq('title', '__CUSTOM_POD_TEMPLATE__')
        .limit(1)
        .single();

      if (existing) {
        podProductId = existing.id;
      } else {
        // Create the sentinel row (only happens once, ever)
        const { data: created, error: createErr } = await supabaseAdmin
          .from('products')
          .insert({
            title: '__CUSTOM_POD_TEMPLATE__',
            base_price: POD_PRICE_PKR,
            category: 'Custom',
            description: 'Sentinel row for custom POD order items. Do not delete.',
            is_pod: true,
            is_active: false, // hidden from storefront queries
          })
          .select('id')
          .single();

        if (createErr || !created) {
          console.error('[checkout] Failed to create POD sentinel product:', createErr);
          return NextResponse.json({ error: 'Could not process custom item.' }, { status: 500 });
        }
        podProductId = created.id;
      }
      console.log('[checkout] Using POD sentinel product_id:', podProductId);
    }

    const verifiedPod = customPodItems.map((item) => {
      subtotal += POD_PRICE_PKR * item.quantity;
      const podRow = {
        product_id:        podProductId!,  // real UUID from sentinel row
        variant_id:        'custom-pod',
        product_title:     'Custom Pehchan Tee (POD)',
        product_image_url: null,
        quantity:          item.quantity,
        unit_price_pkr:    POD_PRICE_PKR,
        pod_customization: {
          ...(item.podCustomizations ?? {}),
          _custom_pod_ref: item.productId,  // original client ID for traceability
        },
        is_pod:            true,
      };
      console.log('[checkout] Custom POD item payload:', podRow);
      return podRow;
    });

    const verifiedItems = [...verifiedRegular, ...verifiedPod];

    const total = subtotal + SHIPPING_PKR;

    // =============================================
    // Simulate payment gateway handshake
    // Replace this block with real SDK calls in Phase 6
    // =============================================
    const gatewayTxnRef = `${gateway.toUpperCase()}-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)
      .toUpperCase()}`;

    // Simulate ~200ms gateway latency
    await new Promise((r) => setTimeout(r, 200));
    // In production: if gateway returns failure, return 402 here.

    // =============================================
    // Write Order + Order Items atomically
    // =============================================
    const { data: order, error: orderError } = await supabaseAdmin
      .from('orders')
      .insert({
        customer_name: shipping.customerName,
        customer_email: shipping.customerEmail,
        customer_phone: shipping.customerPhone,
        address_line1: shipping.addressLine1,
        city: shipping.city,
        province: shipping.province,
        gateway,
        gateway_txn_ref: gatewayTxnRef,
        subtotal_pkr: subtotal,
        shipping_pkr: SHIPPING_PKR,
        total_pkr: total,
        status: 'payment_received',
      })
      .select('id')
      .single();

    if (orderError || !order) {
      console.error('[checkout] Order insert error:', orderError);
      return NextResponse.json({ error: 'Failed to record order.' }, { status: 500 });
    }

    const { error: itemsError } = await supabaseAdmin
      .from('order_items')
      .insert(verifiedItems.map((item) => ({ ...item, order_id: order.id })));

    if (itemsError) {
      console.error('[checkout] Order items insert error:', itemsError);
      // Order was created but items failed — mark as cancelled for investigation
      await supabaseAdmin
        .from('orders')
        .update({ status: 'cancelled' })
        .eq('id', order.id);
      return NextResponse.json({ error: 'Failed to record order items.' }, { status: 500 });
    }

    // =============================================
    // Success
    // =============================================
    return NextResponse.json({
      success: true,
      orderId: order.id,
      gatewayTxnRef,
      verifiedTotal: total,
      shippingCost: SHIPPING_PKR,
    });
  } catch (err) {
    console.error('[checkout] Unhandled error:', err);
    return NextResponse.json({ error: 'Internal server error.' }, { status: 500 });
  }
}
